// Code:
// Mar - same-sex marriage allowed
// CU - same-sex civil unions allowed
// CULite - some same-sex rights
// None - none/unclear
// NoMar - no same-sex marriage by statute
// NoCU - no same-sex civil unions by statute
// NoMarConst - no same-sex marriage in constitution
// NoCUConst - no same-sex civil unions in constitution
// References:
// http://marriagelaw.cua.edu/law/states/AL.cfm
// http://www.domawatch.org/stateissues/alaska/index.html
var marriagedata = {
'AL':[['1998-05', 'NoMar', 'The <a href="http://www.legislature.state.al.us/CodeofAlabama/1975/30-1-19.htm">Marriage Protection Act</a> (Act 98-500) is passed, forbidding same-sex marriage.'], ['2006-06', 'NoCUConst', '<a href="http://www.legislature.state.al.us/CodeofAlabama/Constitution/1901/CA-1470311.htm">Amendment 774</a> to the Alabama constitution is passed, forbidding marriage or other "unions replicating marriage".']],
'AK':[['1998-02', 'Mar', 'In <a href="http://www.marriagewatch.org/Law/cases/brause.cfm">Brause v. Bureau of Vital Statistics</a>, an Alaska Superior Judge ruled choosing a marital partner is a fundamental right that cannot be denied by the state without a compelling reason.'], ['1998-11', 'NoMarConst', '<a href="http://ltgov.state.ak.us/constitution.php?section=1">Amendment to the Alaska Constitution is passed (Article 1, Section 25), forbidding same-sex marriage.']],
'AZ':[['1975-01', 'NoMar', 'A <a href="http://www.buddybuddy.com/t-line-1.html#pro-75">marriage license was given to two Phoenix men.  The state legislature then passed an emergency bill banning same-sex marriage.'], ['2008-11', 'NoMarConst', 'Proposition 102 passed, forbidding same-sex marriage.']],
'AR':[['2004-11', 'NoCUConst', '<a href="http://www.sos.arkansas.gov/ar-constitution/arcamend83/arcamend83.htm">Amendment 83 to the Arkansas Constitution</a> was passed, forbidding same-sex marriage or legal status "which is identical or substantially similar to marital status".']],
'CA':[['1999-09', 'CULite', '<a href="http://www.leginfo.ca.gov/cgi-bin/displaycode?section=fam&group=00001-01000&file=297-297.5">Assembly Bill 26 of 1999</a> passed, granting domestic partners <a href="http://en.wikipedia.org/wiki/Domestic_partnership_in_California#Assembly_Bill_26_of_1999">some rights</a>.'], ['2000-03', 'CULite', '<a href="http://en.wikipedia.org/wiki/California_Proposition_22_(2000)">Proposition 22</a> was passed, forbidding same-sex marriage.'], ['2005-06', 'CU', '<a href="http://en.wikipedia.org/wiki/Domestic_partnership_in_California#Subsequent_changes_and_clarifications">Domestic partner rights were expanded</a> to most of the rights that married couples have.'], ['2008-06', 'Mar', 'The California Supreme Court ruled <a href="http://en.wikipedia.org/wiki/In_re_Marriage_Cases">In re Marriage Cases</a> that the previous statutory same-sex marriage ban was unconstitutional.'], ['2008-11', 'CU', '<a href="http://en.wikipedia.org/wiki/California_Proposition_8_(2008)">Proposition 8</a> passed, amending the state constitution to forbid same-sex marriage.']],
'CO':[['1975-01', 'NoMar', 'After the county clerk of Boulder County allowed six same-sex couples to wed, a law was quickly pushed through to forbid same-sex marriage'], ['2006-11', 'NoMarConst', '<a href="http://www.domawatch.org/stateissues/colorado/index.html">Amendment #43</a> to the Colorado constitution passed, forbidding same-sex marriage.']],
'CT':[['2005-04', 'CU', 'The state legislature passed <a href="http://www.cga.ct.gov/2005/act/Pa/2005PA-00010-R00SB-00963-PA.htm">Public Act No. 05-10</a>, establishing same-sex civil unions.'], ['2008-10', 'Mar', 'The Connecticut supreme court ruled in <a href="http://en.wikipedia.org/wiki/Kerrigan_v._Commissioner_of_Public_Health">Kerrigan v. Commissioner of Public Health</a> that the constitution protects the right of same-sex marriage.']],
'DC':[['2002-01', 'CU', 'The <a href="http://en.wikipedia.org/wiki/Domestic_partnership_in_the_District_of_Columbia">Health Benefits Expansion Act</a> was finally funded by Congress after 10 years, thus allowing domestic partnerships in the District of Columbia.']],
'DE':[['1996-11', 'NoMar', 'The Marriage Protection Act added a <a href="http://delcode.delaware.gov/title13/c001/sc01/index.shtml">statute forbidding same-sex marriage</a>.']],
'FL':[['1997-01', 'NoMar', 'The <a href="http://www.leg.state.fl.us/Statutes/index.cfm?App_mode=Display_Statute&Search_String=&URL=Ch0741/SEC212.HTM&Title">Defense of Marriage law</a> passed, forbidding same-sex marriage.'], ['2008-11', 'NoCUConst', 'The <a href="http://ballotpedia.org/wiki/index.php/Florida_Marriage_Amendment_(2008)">Florida Marriage Amendment</a> to the Florida constitution passed, forbidding same-sex marriage and possibly same-sex civil unions.']],
'GA':[['1996-01', 'NoMar', 'The <a href="http://law.gsu.edu/lawreview/index/archives/show/?art=21-1/21-1_Constitution_SchaferAlexander.htm">Georgia General Assembly</a> enacted <a href="http://law.onecle.com/georgia/19/19-3-3.1.html">Title 19, Section 19-3-3.1</a>, forbidding same-sex marriage.'], ['2004-11', 'NoCUConst', 'An act amending the Georgia constitution to <a href="http://www.domawatch.org/stateissues/georgia/index.html">forbid same-sex marriage and possibly civil unions</a> passed.']],
'HI':[['1996-12', 'None', 'The Hawaii Supreme Court ruled in <a href="http://hawaii.gov/jud/20371.htm">Baehr v. Miike</a> that forbidding same-sex marriage violated the state constitution; however, they did not allow same-sex marriage at that time.'], ['1997-01', 'CULite', '<a href="http://en.wikipedia.org/wiki/Reciprocal_beneficiary_relationships_in_Hawaii">Reciprocal beneficiary relationships</a> were created in Hawaii, allowing couples who cannot legally get married (including same-sex couples) to have a limited number of rights and benefits.'], ['1998-11', 'CULite', '<a href="http://en.wikipedia.org/wiki/Hawaii_Constitutional_Amendment_2_(1998)">Hawaii Constitutional Amendment 2</a> passed, giving the state legislature the right to enact a same-sex marriage ban.  The state legislature did so shortly thereafter.']],
'ID':[['1996-01', 'NoCU', 'The <a href="http://marriagelaw.cua.edu/law/states/ID.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage and possibly civil unions.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Idaho_Amendment_2_(2006)">Idaho Amendment 2</a> passed, forbidding same-sex marriage or civil unions in the state constitution.']],
'IL':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/IL.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.']],
'IN':[['1997-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/IN.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.']],
'IA':[['1998-04', 'NoMar', '<a href="http://marriagelaw.cua.edu/law/states/IA.cfm">1998 Ia H.F. 382</a> passed, forbidding same-sex marriage.'], ['2007-08', 'Mar', 'A ruling in the <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_in_Iowa">Varnum v. Brien</a> case allowed same-sex marriage for a short time in Polk County in Iowa.'], ['2007-09', 'NoMar', 'The judge then ordered a stay of his ruling pending the county\'s appeal.  As of March 2009, the case is before the Iowa Supreme Court.']],
'KS':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/KS.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2005-04', 'NoMarConst', '<a href="http://www.domawatch.org/stateissues/kansas/index.html">Article 15, Section 16 of the Kansas Constitution</a> passed, forbidding same-sex marriage.']],
'KY':[['1998-04', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/KY.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Kentucky_Constitutional_Amendment_1_(2004)">Constitutional Amendment 1</a> passed, forbidding same-sex marriage or civil unions.']],
'LA':[['1999-07', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/LA.cfm">Marriage Recognition Act</a> passed, forbidding same-sex marriage.'], ['2004-09', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Louisiana_Constitutional_Amendment_1_(2004)">Constitutional Amendment 1</a> passed, forbidding same-sex marriage or civil unions.'], ['2004-10', 'NoMar', 'A district judge in Baton Rouge <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_legislation_in_the_United_States_by_state#Louisiana">struck down the constitutional amendment</a>, finding that it violated a provision of the state constitution requiring amendments to only cover one subject.'], ['2005-01', 'NoCUConst', 'The Louisiana Supreme Court <A href="http://en.wikipedia.org/wiki/Same-sex_marriage_legislation_in_the_United_States_by_state#Louisiana">overruled the district judge</a> and reinstated <a href="http://en.wikipedia.org/wiki/Louisiana_Constitutional_Amendment_1_(2004)">Constitutional Amendment 1</a>.']],
'ME':[['1997-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/ME.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2004-06', 'CULite', '<a href="http://en.wikipedia.org/wiki/Domestic_partnership_in_Maine">Domestic partnerships were established in Maine</a>, providing some rights to same-sex couples.']],
'MD':[['1973-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/MD.cfm">Maryland Statutes Family Law</a> forbids same-sex marriage.'], ['2007-09', 'NoMar', 'The Maryland Supreme Court <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_in_Maryland#Conaway_v._Deane_.26_Polyak">ruled in Conaway v. Deane &amp; Polyak</a> that the prohibition on same-sex marriage did not violate Article 46 of the Maryland Declaration of Rights (which forbids discrimentation based on sex).'], ['2008-07', 'NoMar', 'The Maryland General Assembly passed a bill <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_in_Maryland#Domestic_partnership_legislation">establishing a very weak form of domestic partnerships</a> although there is no statewide registry.']],
'MA':[['2003-11', 'None', 'The Massachusetts Supreme Court ruled in <a href="http://en.wikipedia.org/wiki/Goodridge_v._Department_of_Public_Health">Goodridge v. Department of Public Health</a> that the state must allow same-sex marriage within 180 days.'], ['2004-05', 'Mar', 'The ruling in <a href="http://en.wikipedia.org/wiki/Goodridge_v._Department_of_Public_Health">Goodridge v. Department of Public Health</a> takes effect, and same-sex couples are allowed to marry.']],
'MI':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/MI.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Michigan_State_Proposal_-_04-2_(2004)">Michigan State Proposal - 04-2</a> passed, forbidding same-sex marriage or civil unions or any sort of domestic partnership benefits.']],
'MN':[['1997-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/MN.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.']],
'MS':[['1997-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/MS.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoMarConst', '<a href="http://en.wikipedia.org/wiki/Mississippi_Amendment_1_(2004)">Mississippi Amendment 1</a> passed, amending the Mississippi Constitution to forbid same-sex marriage.']],
'MO':[['2001-07', 'NoMar', '<a href="http://marriagelaw.cua.edu/law/states/MO.cfm">2001 Mo. H.B. 157</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoMarConst', '<a href="http://en.wikipedia.org/wiki/Missouri_Constitutional_Amendment_2_(2004)">Missouri Constitutional Amendment 2</a> passed, forbidding same-sex marriage.']],
'MT':[['1997-01', 'NoCU', 'The <a href="http://marriagelaw.cua.edu/law/states/MT.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage or civil unions.'], ['2004-11', 'NoMarConst', '<a href="http://en.wikipedia.org/wiki/Montana_Initiative_96_(2004)">Montana Initiative 96</a> passed, amending the Montana Constitution to forbid same-sex marriage.']],
'NE':[['2000-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Nebraska_Initiative_Measure_416_(2000)">Nebraska Initiative Measure 416</a> passed, amending the Nebraska Constitution to forbid same-sex marriage or civil unions.'], ['2005-05', 'None', 'A federal judge in Omaha <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_legislation_in_the_United_States_by_state#Nebraska">struck down the ban on same-sex marriage and civil unions</a>.'], ['2006-07', 'NoCUConst', 'The 8th Circuit Court of Appeals <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_legislation_in_the_United_States_by_state#Nebraska">reinstates the ban</a> on same-sex marriage and civil unions.']],
'NV':[['2002-11', 'NoMarConst', '<a href="http://en.wikipedia.org/wiki/Nevada_Question_2_(2002)">Nevada Question 2</a> amended the Nevada Constitution to forbid same-sex marriage. (this was done in two consecutive elections, as required by Nevada law)']],
'NH':[['1997-07', 'NoMar', 'Section 457 (<a href="http://law.justia.com/newhampshire/codes/nhtoc-xliii/457-1.html">part 1</a>, <a href="http://law.justia.com/newhampshire/codes/nhtoc-xliii/457-2.html">part 2</a>) forbids same-sex marriage.'], ['2007-05', 'NoMar', 'The governor <a href="http://www.concordmonitor.com/apps/pbcs.dll/article?AID=/20070531/BREAK/70531001/1030">signed a civil unions bill (HB 437) into law</a> to take effect in 2008.  It was the first state to enact civil unions without a lawsuit or a threat of one.'], ['2008-01', 'CU', 'Per <a href="http://www.hrc.org/your_community/1329.htm">HB 437</a>, civil unions are given out to same-sex couples.']],
'NJ':[['2006-10', 'None', 'The New Jersey Supreme Court ruled in <a href="http://en.wikipedia.org/wiki/Lewis_v._Harris">Lewis v. Harris</a> that the state law regarding marriage was unconstitutional, and the legislature had 6 months to either allow same-sex marriage or civil unions.'], ['2007-02', 'CU', 'The <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_in_New_Jersey#Civil_Union_Act">Civil Union Act</a> passed the New Jersey Legislature and was signed by the governor, allowing for same-sex civil unions.']],
'NM':[['2004-02', 'None', 'A Sandoval County clerk began <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_in_New_Mexico#2004</a>giving out same-sex marriage licenses</a> since New Mexico marriage law does not mention gender.  By the end of the day, the state attorney general ruled the marriages were invalid.']],
'NY':[['2007-04', 'None', 'The governor <a href="http://www.domawatch.org/stateissues/newyork/index.html">introduced a same-sex marriage bill A08590</a> to the New York State Legislature, which passed the State Assembly but failed in the State Senate.'], ['2008-05', 'None', 'The governor gave an <a href="http://www.nytimes.com/2008/05/29/nyregion/29marriage.html?pagewanted=print">executive order</a> instructing state agencies to recognize same-sex marriages performed in other states.']],
'NC':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/NC.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.']],
'ND':[['1997-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/ND.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/North_Dakota_Constitutional_Measure_1_(2004)">North Dakota Constitutional Measure 1</a> passed, forbidding same-sex marriage or civil unions.']],
'OH':[['2004-02', 'NoCU', '<a href="http://www.legislature.state.oh.us/bills.cfm?ID=125_HB_272">HB 272</a> passed, forbidding same-sex marriage or civil unions.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Ohio_State_Issue_1_(2004)">Ohio State Issue 1</a> passed, amending the Ohio State Constitution to forbid same-sex marriage or civil unions.']],
'OK':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/OK.cfm">Marriage Recognition Act</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Oklahoma_State_Question_711_(2004)">Oklahoma State Question 711</a> passed, amending the Oklahoma Constitution to forbid same-sex marriage or civil unions.']],
'OR':[['2004-11', 'NoMarCU', '<a href="http://en.wikipedia.org/wiki/Oregon_Ballot_Measure_36_(2004)">Oregon Ballot Measure 34</a> passed, amending the Oregon Constitution to forbid same-sex marriage.'], ['2007-05', 'NoMar', 'The governor <a href="http://en.wikipedia.org/wiki/Civil_unions_in_Oregon">signed a bill establishing domestic partnerships</a> to take effect in 2008.'], ['2008-02', 'CU', 'The <a href="http://en.wikipedia.org/wiki/Civil_unions_in_Oregon">bill took effect</a>, allowing for same-sex domestic partnerships.']],
'PA':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/PA.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.']],
'RI':[['2007-01', 'None', 'A <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_in_Rhode_Island#Recent_legislative_proposals">number of bills were introduced allowing for same-sex marriage or civil unions</a>, but none were passed.']],
'SC':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/SC.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2006-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/South_Carolina_Amendment_1_(2006)">South Carolina Amendment 1</a> passed, amending the South Carolina Constitution to forbid same-sex marriage or civil unions.']],
'SD':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/SD.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2006-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/South_Dakota_Amendment_C_(2006)">South Dakota Amendment C</a> passed, amending the South Dakota Constitution to forbid same-sex marriage or civil unions.']],
'TN':[['1996-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/TN.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2006-11', 'NoMarConst', '<a href="http://en.wikipedia.org/wiki/Tennessee_Amendment_1_of_2006">Tennessee Amendment 1</a> passed, amending the Tennessee Constitution to forbid same-sex marriage.']],
'TX':[['1997-04', 'NoMar', '<a href="http://tlo2.tlc.state.tx.us/statutes/docs/FA/content/htm/fa.001.00.000002.00.htm#2.001.00">Acts 1997, 75th Leg., ch. 7, Sec. 1, eff. April 17, 1997</a> passed, forbidding same-sex marriage.'], ['2003-09', 'NoCU', '<a href="http://tlo2.tlc.state.tx.us/statutes/docs/FA/content/htm/fa.001.00.000006.00.htm#12369.10674">Acts 2003, 78th Leg., ch. 124, Sec. 1, eff. Sept. 1, 2003</a> passed, forbidding same-sex marriage or civil unions.'], ['2005-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Texas_proposition_2_(2005)">Texas Proposition 2</a> passed, amending the Texas Constitution to forbid same-sex marriage or civil unions.']],
'UT':[['1995-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/UT.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.'], ['2004-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Utah_Constitutional_Amendment_3">Utah Constitutional Amendment 3</a> passed, amending the Utah Constitution to forbid same-sex marriage or civil unions.']],
'VT':[['1999-01', 'NoMar', '<a href="http://www.leg.state.vt.us/statutes/fullsection.cfm?Title=15&Chapter=001&Section=00008">1999, No. 91 (Adj. Sess.), § 25</a> passed, forbidding same-sex marriage.'], ['1999-12', 'NoMar', 'In <a href="http://en.wikipedia.org/wiki/Baker_v._Vermont">Baker v. Vermont</a>, the Vermont Supreme Court ruled that same-sex couples had to be given the rights of married couples, whether it be same-sex marriage or civil unions.'], ['2000-07', 'CU', 'The Vermont <a href="http://en.wikipedia.org/wiki/Civil_unions_in_Vermont">Civil union law</a> went into effect, allowing for same-sex civil unions.'], ['2009-02', 'CU', 'A <a href="http://www.leg.state.vt.us/database/status/summary.cfm?Bill=H.0275&Session=2008">bill to permit same-sex marriage</a> was introduced into the state legislature, but the governor has promised to veto it.  It is unclear whether the legislature will override the governor\'s veto.']],
'VA':[['1975-01', 'NoMar', 'The <a href="http://en.wikipedia.org/wiki/Same-sex_marriage_legislation_in_the_United_States_by_state#Virginia">Code of Virginia was amended</a> to forbid same-sex marriage.'], ['2004-01', 'NoCU', 'The <a href="http://leg1.state.va.us/cgi-bin/legp504.exe?000+cod+20-45.3">Code of Virginia was amended</a> to forbid same-sex civil unions as well.'], ['2006-11', 'NoCUConst', 'The <a href="http://en.wikipedia.org/wiki/Marshall-Newman_Amendment">Marshall-Newman Amendment</a> passed, amending the Virginia Constitution to forbid same-sex marriage or civil unions or any private contracts that would have the same effect.']],
'WA':[['1998-01', 'NoMar', 'The <a href="http://apps.leg.wa.gov/RCW/default.aspx?cite=26.04.010">Defense of Marriage Act</a> passed, forbidding same-sex marriage.'], ['2006-07', 'NoMar', 'The Washington Supreme Court ruled in <a href="http://en.wikipedia.org/wiki/Andersen_v._King_County">Andersen v. King County</a> that the Defense of Marriage Act was constitutional.'], ['2007-07', 'CULite', 'The state legislature passed a <a href="http://en.wikipedia.org/wiki/Domestic_partnership_in_Washington">domestic partnership law</a>, providing some benefits of marriage to same-sex couples.']],
'WV':[['2000-01', 'NoMar', 'The <a href="http://marriagelaw.cua.edu/law/states/WV.cfm">Marriage Protection Act</a> passed, forbidding same-sex marriage.']],
'WI':[['1979-01', 'NoMar', 'The <a href="http://nxt.legis.state.wi.us/nxt/gateway.dll/Statutes Related/Wisconsin Statutes/13831/13832?f=templates$fn=document-frame.htm$3.0$q=[field folio-destination-name%3A\'765.001\']$uq=$x=Advanced$up=1#LPHit1">Wisconsin Family Code</a> forbids same-sex marriage.'], ['2006-11', 'NoCUConst', '<a href="http://en.wikipedia.org/wiki/Wisconsin_Referendum_1_(2006)">Wisconsin Referendum 1</a> passed, amending the Wisconsin Constitution to forbid same-sex marriage or civil unions.']],
'WY':[['1901-01', 'NoMar', '(date unknown) The Wyoming <a href="http://legisweb.state.wy.us/statutes/titles/Title20/Title20.htm">Domestic Relations Code</a> forbids same-sex marriage.']]
};
